econovation fighting
JNU-econovation/2021-1-I-AM-GROUND pull request #14
Opened 2021-05-28 07:58 UTC by kok1909kok

안녕하세요 저는 밝고 긍정적인 에너자이저 무적산공 강다은입니다!

2021-05-28 09:46 UTC, mywnajsldkf approved these changes
다은님의 첫 Pull Request 축하드립니다! 
비대면이지만 밝음의 에너지가 느껴지는 다은님의 열정이 느껴져서 읽고 있는 저도 웃음이 나오는 자기소개였어요ㅎㅎ 고맙습니다. 
빨리 코로나 끝나서 다은님의 에너지를 4D로 느끼고 싶네요! 주말 잘 보내세요

2021-05-28 09:46 UTC, mywnajsldkf commented on profile/kok1909kok.md
> +좀 더 자세하게 자신에 대해서 소개해주세요안녕하세요! 에코노베이션 21기 강다은입니다! 저는 산업공학과 2학년 20학번 강다은이에요! 무적산공입니다 ^>^ 일단 에코노베이션 동아리에 들어오게 되어서 너무 자랑스럽고 행복합니다! 처음 면접보는 것도 너무 떨려서 머리가 새하얘졌던 기억이 새록새록 떠올라요.. 성혁님꼐서 당황하지말라고 괜찮다고 토닥토닥해주셨던
다은님!! 반갑습니다 :)

2021-05-28 09:46 UTC, mywnajsldkf commented on profile/kok1909kok.md
> +제가 처음 git를 접해보는거라 많이 서툴지만 같은 팀원 서현님과 같이 하니 무서울게 하나도 없어요! 저에 대한 이야기를 동아리에서 처음 하는 거라 무슨 말을 해야할지 더둑 더 고민을 하게 되었던 거 같아요!
오오!!! 멋진 팀이군요!

2021-05-28 09:46 UTC, mywnajsldkf commented on profile/kok1909kok.md
> +아싸 에코노베이션 동아리 들어와서 너무 행복하다!!! 진짜 좋은 사람들 너무너무 많다 .. 이렇게 나도 좋은 사람 되야지! 생각했어요 그 생각은 지금도 여전합니다! 다들 너무 좋으세요 정말 진지로 진심입니다^.^
우와!! 다음 기수에 선배미 뿜뿜하실 다은님이 너무 기대 되는걸요?! 흐흐

2021-05-28 09:46 UTC, mywnajsldkf commented on profile/kok1909kok.md
> +제 멘토님 중 한분인 영주님이 "밑바닥부터 시작하는 딥러닝"책도 추천해주셔서 그 책과 함께 인공지능을 공부하면서 입문하는 중입니다!
오오!!! 어려운 분야인데 열심히 하시는 모습이 대단합니당

2021-05-28 09:46 UTC, mywnajsldkf commented on profile/kok1909kok.md
> +저는 운동하는 것을 되게 좋아하는데요! 그 중에서 저는 크로스핏 이라는 운동을 하고 있어요! 겉으로 보기에는 되게 역동적이고 격한 운동으로 보이지만 그거 맞아요 . .
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ다은님 글이 무척 재미있네요...! 크로스핏 해본 적은 없지만 생각만 해도 쓰러질 것 같아요

2021-05-28 09:46 UTC, mywnajsldkf commented on profile/kok1909kok.md
> +되게 이 자기소개 쓰는데 까지만해도 정말 많이 고민하고 git에 올리는 것도 아직 서툴러서 서현님께 도움 요청했어요!
흐흐! 고민 많이 하신게 느껴집니다! 팀원분과 함께 으쌰으쌰하시는 것 같아 보기좋아용

2021-05-28 09:46 UTC, mywnajsldkf commented on profile/kok1909kok.md
> +오늘 하루도 모두 수고하셨습니다! 행복한 주말 보내세요 :)
다은님두요! 💟💟

2021-05-28 11:35 UTC, mywnajsldkf requested changes
어머! 다은님 다시 보니 PR 제목을 수정하셔야 하겠군요! 
[README.md](https://github.com/JNU-econovation/2021-1-I-AM-GROUND)를 확인해주세요! 
<img width="755" alt="스크린샷 2021-05-28 오후 8 35 28" src="https://user-images.githubusercontent.com/47661695/119978162-44ac4c80-bff4-11eb-9f4a-5fb5b0d88249.png">
이 부분 충족하시면 다시 approve 해드리겠습니다!

2021-05-28 15:40 UTC, spiderq2697 approved these changes

2021-05-28 15:40 UTC, spiderq2697 commented on profile/kok1909kok.md
> +좀 더 자세하게 자신에 대해서 소개해주세요안녕하세요! 에코노베이션 21기 강다은입니다! 저는 산업공학과 2학년 20학번 강다은이에요! 무적산공입니다 ^>^ 일단 에코노베이션 동아리에 들어오게 되어서 너무 자랑스럽고 행복합니다! 처음 면접보는 것도 너무 떨려서 머리가 새하얘졌던 기억이 새록새록 떠올라요.. 성혁님꼐서 당황하지말라고 괜찮다고 토닥토닥해주셨던
커밋내용부터 파이팅 넘치는데요??ㅎㅎㅎ 파이팅입니다ㅋㅋㅋ
성혁님이 아주 좋은 면접관이었네요ㅎㅎ

2021-05-28 15:40 UTC, spiderq2697 commented on profile/kok1909kok.md
> +아싸 에코노베이션 동아리 들어와서 너무 행복하다!!! 진짜 좋은 사람들 너무너무 많다 .. 이렇게 나도 좋은 사람 되야지! 생각했어요 그 생각은 지금도 여전합니다! 다들 너무 좋으세요 정말 진지로 진심입니다^.^
나날이 에코노에 긍정적인 에너지를 퍼트리실 다은님의 모습이 기대됩니다ㅎㅎ

2021-05-28 15:40 UTC, spiderq2697 commented on profile/kok1909kok.md
> +제 멘토님 중 한분인 영주님이 "밑바닥부터 시작하는 딥러닝"책도 추천해주셔서 그 책과 함께 인공지능을 공부하면서 입문하는 중입니다!
크.... 정말 인공지능 어려운데 끈기있게 하시는 모습이 정말 멋있습니다ㅎㅎ

2021-05-28 15:40 UTC, spiderq2697 commented on profile/kok1909kok.md
> +저는 운동하는 것을 되게 좋아하는데요! 그 중에서 저는 크로스핏 이라는 운동을 하고 있어요! 겉으로 보기에는 되게 역동적이고 격한 운동으로 보이지만 그거 맞아요 . .
크로스핏.... 기초체력없으면 몸 아작난다는 크로스핏.... 저도 담에 꼭 해보려구요ㅎㅎ

2021-05-28 19:42 UTC, mywnajsldkf commented
다은님! 피드백 반영해주셨네요 :) 감사합니다 approve 해드릴게요!!

2021-05-28 19:43 UTC, mywnajsldkf approved these changes

2021-05-31 13:39 UTC, gxxrxn approved these changes

2021-05-31 13:39 UTC, gxxrxn commented on profile/kok1909kok.md
> +좀 더 자세하게 자신에 대해서 소개해주세요안녕하세요! 에코노베이션 21기 강다은입니다! 저는 산업공학과 2학년 20학번 강다은이에요! 무적산공입니다 ^>^ 일단 에코노베이션 동아리에 들어오게 되어서 너무 자랑스럽고 행복합니다! 처음 면접보는 것도 너무 떨려서 머리가 새하얘졌던 기억이 새록새록 떠올라요.. 성혁님꼐서 당황하지말라고 괜찮다고 토닥토닥해주셨던
무적산공...!!! 인정합니다!!!😆👍

2021-05-31 13:39 UTC, gxxrxn commented on profile/kok1909kok.md
> +처음 에코노 동아리 면접볼때가 생각나요!
저도 다은님 긴장하시던 모습이 생각나네요ㅎㅎ😆 사실 면접관분들도 엄청 긴장했었답니다!!ㅎㅎ

2021-05-31 13:39 UTC, gxxrxn commented on profile/kok1909kok.md
> +제 멘토님 중 한분인 영주님이 "밑바닥부터 시작하는 딥러닝"책도 추천해주셔서 그 책과 함께 인공지능을 공부하면서 입문하는 중입니다!
첫 프로젝트로 인공지능을 선택하시다니 진짜 너무 멋져요!!! 서현님과 함께 열심히 하시는 모습 너무 보기 좋은 것 같아요~ㅎㅎ🥰

2021-05-31 13:39 UTC, gxxrxn commented on profile/kok1909kok.md
> +저는 운동하는 것을 되게 좋아하는데요! 그 중에서 저는 크로스핏 이라는 운동을 하고 있어요! 겉으로 보기에는 되게 역동적이고 격한 운동으로 보이지만 그거 맞아요 . .
와.. 운동.. 크로스핏.. 리스펙...👏

2021-05-31 13:39 UTC, gxxrxn commented on profile/kok1909kok.md
> +사람들 만나서 이야기하는 것도 되게 좋아해서 기회되면 동아리분들도 많이 만나서 이야기하고 싶어요 ~
저도 얼른 다은님 만나고 싶네요ㅠㅠ 그래서 저는 렛츠파워업 너무 기대하고 있답니다!! 😆

2021-05-31 13:39 UTC, gxxrxn commented on profile/kok1909kok.md
> +오늘 하루도 모두 수고하셨습니다! 행복한 주말 보내세요 :)
ㅎㅎ 다은님의 긍정적인 에너지가 너무 너무 좋네요!! 항상 화이팅입니다!! 💜

2021-07-02 09:13 UTC, merged

2021-07-02 09:13 UTC, mywnajsldkf commented
넘 귀여우시고 존재자체가 힐링인 다은님을 알게되어 기뻐요! 머지 축하드려요!!