채상엽(saint6839)
JNU-econovation/2021-1-I-AM-GROUND pull request #3
Opened 2021-05-15 07:25 UTC by saint6839

안녕하세요. 21기 채상엽입니다.

2021-05-15 09:02 UTC, mywnajsldkf approved these changes
상엽님 안녕하세요! 자기소개 잘 봤습니다.
에코노베이션에 들어온 것을 환영합니다. 
동아리 활동을 통해 앱 개발자로 거듭나시길 응원하겠습니다!!

2021-05-15 09:02 UTC, mywnajsldkf commented on profile/sangyeop.md
> +지난 겨울 방학을 통해 앱 프로그래밍에 관심이 생겨, 자바와 안드로이드 스튜디오로 공부를 하고 있습니다.
앱이라면 안드로이드 앱 외에 다른 부분에도 관심있으시나요?!

2021-05-15 09:02 UTC, mywnajsldkf commented on profile/sangyeop.md
> +이번 학기에는 첫 프로젝트로 Todo 어플리케이션을 구현합니다. 가장 단순하지만 기본이자 필수적인 기능들을 포함하고 있기 때문에, 첫 프로젝트 주제로 선정하였습니다. 대신에 저희는 완성도를 높히는 것에 초점을 맞출 계획입니다.
저도 이번 학기에 앱 프로젝트를 하는데 반갑습니다!

2021-05-15 09:02 UTC, mywnajsldkf commented on profile/sangyeop.md
> +에코노베이션에서 활동한지 그리 오래 되지 않았지만, 계속해서 좋은 기회들이 다가오고 좋은 정보들을 제공해주셔서 너무 감사하게 생각하고 있습니다. 앞으로도 행사에 최대한 참여하려고 노력하겠습니다. 마지막으로 방학때 코틀린 스터디가 꾸려지면 정말 좋을 것 같습니다 !
에코노베이션 들어온 것을 확인합니다!!! 코틀린 스터디도 하루 빨리 나오면 좋겠네요!

2021-05-15 09:37 UTC, saint6839 commented on profile/sangyeop.md
> +지난 겨울 방학을 통해 앱 프로그래밍에 관심이 생겨, 자바와 안드로이드 스튜디오로 공부를 하고 있습니다.
아직 많이 모자라서, 우선은 안드로이드 스튜디오에만 전념하고 있어요 !. 그나저나 인덱스 단위로 나눠서 코멘트를 남길수도 있나보네요. 신기합니다 ㅎㅎ

2021-05-15 09:38 UTC, saint6839 commented on profile/sangyeop.md
> +이번 학기에는 첫 프로젝트로 Todo 어플리케이션을 구현합니다. 가장 단순하지만 기본이자 필수적인 기능들을 포함하고 있기 때문에, 첫 프로젝트 주제로 선정하였습니다. 대신에 저희는 완성도를 높히는 것에 초점을 맞출 계획입니다.
반갑습니다 ~~!

2021-05-15 09:39 UTC, saint6839 commented on profile/sangyeop.md
> +에코노베이션에서 활동한지 그리 오래 되지 않았지만, 계속해서 좋은 기회들이 다가오고 좋은 정보들을 제공해주셔서 너무 감사하게 생각하고 있습니다. 앞으로도 행사에 최대한 참여하려고 노력하겠습니다. 마지막으로 방학때 코틀린 스터디가 꾸려지면 정말 좋을 것 같습니다 !
너무 좋다고 말이 많아서 꼭 공부해보고 싶네요 ~!

2021-05-16 13:45 UTC, ummaeha commented
상엽님 반갑습니당~~ 이 글을 통해 코틀린 스터디를 함께할 수 있는 스터디원을 잘 구하실수 있길 바랍니다~!!

approve를 하기전 PR제목 변경 요청 드립니당 ~ ( 지금 제목을 수정하는 것은 중요하지 않을 수 있지만, 나중에 정말 코드 머지를 위한 pull request를 날릴때, 제목을 명시적, 규칙에 맞게 작성하는 것 그리고 수정사항을 요청했을때 내용을 수정하고, 또 approve받는 과정을 경험해보는 것은 중요한 것 같아서 요청드려요 😄  )

[README에 나와있는 규칙]
> 제목은 '자신의 이름(자신의 GitHub 아이디) - 자기 소개'로 해주세요.
> ex) 김정인(mywnajsldkf) - 자기소개

2021-05-16 14:02 UTC, ummaeha requested changes
![](https://media4.giphy.com/media/tIeCLkB8geYtW/giphy.gif)

상엽님 반갑습니당~~ 이 글을 통해 코틀린 스터디를 함께할 수 있는 스터디원을 잘 구하실수 있길 바랍니다~!!

approve를 하기전 PR제목 변경 요청 드립니당 ~ ( 지금 제목을 수정하는 것은 중요하지 않을 수 있지만, 나중에 정말 코드 머지를 위한 pull request를 날릴때, 제목을 명시적, 규칙에 맞게 작성하는 것 그리고 수정사항을 요청했을때 내용을 수정하고, 또 approve받는 과정을 경험해보는 것은 중요한 것 같아서 요청드려요 😄 )

[README에 나와있는 규칙]

제목은 '자신의 이름(자신의 GitHub 아이디) - 자기 소개'로 해주세요.
ex) 김정인(mywnajsldkf) - 자기소개

2021-05-16 16:00 UTC, mywnajsldkf approved these changes

2021-05-16 16:01 UTC, mywnajsldkf commented
> ![](https://camo.githubusercontent.com/2b6bc82ca348cb81e1cef9a2262f08c6d534d11b630c8d2729a2d7a315cd812d/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f744965434c6b423867655974572f67697068792e676966)
> 
> 상엽님 반갑습니당~~ 이 글을 통해 코틀린 스터디를 함께할 수 있는 스터디원을 잘 구하실수 있길 바랍니다~!!
> 
> approve를 하기전 PR제목 변경 요청 드립니당 ~ ( 지금 제목을 수정하는 것은 중요하지 않을 수 있지만, 나중에 정말 코드 머지를 위한 pull request를 날릴때, 제목을 명시적, 규칙에 맞게 작성하는 것 그리고 수정사항을 요청했을때 내용을 수정하고, 또 approve받는 과정을 경험해보는 것은 중요한 것 같아서 요청드려요 😄 )
> 
> [README에 나와있는 규칙]
> 
> > 제목은 '자신의 이름(자신의 GitHub 아이디) - 자기 소개'로 해주세요.
> > ex) 김정인(mywnajsldkf) - 자기소개

goodgood!!! 좋은 의견입니다 
그나저나 저 움짤(?) 넘 귀엽네요...!!!! 
어떻게 쓰시는 건가요?! #

2021-05-17 06:29 UTC, saint6839 commented
> ![](https://camo.githubusercontent.com/2b6bc82ca348cb81e1cef9a2262f08c6d534d11b630c8d2729a2d7a315cd812d/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f744965434c6b423867655974572f67697068792e676966)
> 
> 상엽님 반갑습니당~~ 이 글을 통해 코틀린 스터디를 함께할 수 있는 스터디원을 잘 구하실수 있길 바랍니다~!!
> 
> approve를 하기전 PR제목 변경 요청 드립니당 ~ ( 지금 제목을 수정하는 것은 중요하지 않을 수 있지만, 나중에 정말 코드 머지를 위한 pull request를 날릴때, 제목을 명시적, 규칙에 맞게 작성하는 것 그리고 수정사항을 요청했을때 내용을 수정하고, 또 approve받는 과정을 경험해보는 것은 중요한 것 같아서 요청드려요 😄 )
> 
> [README에 나와있는 규칙]
> 
> > 제목은 '자신의 이름(자신의 GitHub 아이디) - 자기 소개'로 해주세요.
> > ex) 김정인(mywnajsldkf) - 자기소개

깃허브 사용이 서툴러서 이것 저것 빠뜨린 부분들이 있었네요 ㅠㅠ. 좋은 피드백 해주셔서 감사합니다 ㅎㅎ!

2021-05-18 17:02 UTC, ummaeha approved these changes

2021-05-20 17:10 UTC, JUDONGHYEOK approved these changes

2021-05-20 17:12 UTC, JUDONGHYEOK commented
에코노 21기 열정가이 상엽님 자기소개 잘봤어요 자기소개만으로도 열정이 느껴지네요~:fire:
이번 학기 프로젝트도 화이팅입니다!!

2021-05-21 10:43 UTC, asong57 approved these changes
에코노에 오신 것을 환영합니다 상엽님!!
이번 학기 프로젝트 화이팅입니다~~!

2021-05-21 10:43 UTC, asong57 commented on profile/saint6839.md
> +안녕하세요 산업공학과 3학년 재학중인 16학번 채상엽입니다.
산공 화이팅!!ㅎㅎ

2021-05-21 10:43 UTC, asong57 commented on profile/saint6839.md
> +이번 학기에는 첫 프로젝트로 Todo 어플리케이션을 구현합니다. 가장 단순하지만 기본이자 필수적인 기능들을 포함하고 있기 때문에, 첫 프로젝트 주제로 선정하였습니다. 대신에 저희는 완성도를 높히는 것에 초점을 맞출 계획입니다.
패스트보이즈팀 응원합니다!!

2021-05-21 10:43 UTC, asong57 commented on profile/saint6839.md
> +에코노베이션에서 활동한지 그리 오래 되지 않았지만, 계속해서 좋은 기회들이 다가오고 좋은 정보들을 제공해주셔서 너무 감사하게 생각하고 있습니다. 앞으로도 행사에 최대한 참여하려고 노력하겠습니다. 마지막으로 방학때 코틀린 스터디가 꾸려지면 정말 좋을 것 같습니다 !
에코노 포에버~~
타이밍 맞으면 같이 코틀린 공부해요!ㅎㅎ

2021-05-21 15:49 UTC, vvvpiano approved these changes
(채)상엽님 반갑습니다~~ 에코노베이션에서 같이 즐겁게 활동했으면 좋겠어요!! Fast-boys답게 자기소개도 굉장히 빠르게 올리셨네요!!ㅋㅋㅋ

2021-05-21 15:49 UTC, vvvpiano commented on profile/saint6839.md
> +안녕하세요 산업공학과 3학년 재학중인 16학번 채상엽입니다.
오호 16학번이시군요! 반갑습니다 상엽님~~~

2021-05-21 15:49 UTC, vvvpiano commented on profile/saint6839.md
> +이번 학기에는 첫 프로젝트로 Todo 어플리케이션을 구현합니다. 가장 단순하지만 기본이자 필수적인 기능들을 포함하고 있기 때문에, 첫 프로젝트 주제로 선정하였습니다. 대신에 저희는 완성도를 높히는 것에 초점을 맞출 계획입니다.
겨울방학에 관심이 생기셨는데 봄에 바로 동아리에 가입하시다니! 실행력이 좋으시네요ㅎㅎ

2021-05-21 15:49 UTC, vvvpiano commented on profile/saint6839.md
> +에코노베이션에서 활동한지 그리 오래 되지 않았지만, 계속해서 좋은 기회들이 다가오고 좋은 정보들을 제공해주셔서 너무 감사하게 생각하고 있습니다. 앞으로도 행사에 최대한 참여하려고 노력하겠습니다. 마지막으로 방학때 코틀린 스터디가 꾸려지면 정말 좋을 것 같습니다 !
코틀린 스터디 좋네요ㅎㅎ 상엽님께서 앱개발자들으 모아서 한번 꾸려보시는건 어떤가요?ㅎㅎ

2021-05-22 05:03 UTC, saint6839 commented on profile/saint6839.md
> +에코노베이션에서 활동한지 그리 오래 되지 않았지만, 계속해서 좋은 기회들이 다가오고 좋은 정보들을 제공해주셔서 너무 감사하게 생각하고 있습니다. 앞으로도 행사에 최대한 참여하려고 노력하겠습니다. 마지막으로 방학때 코틀린 스터디가 꾸려지면 정말 좋을 것 같습니다 !
> 에코노 포에버~~
> 타이밍 맞으면 같이 코틀린 공부해요!ㅎㅎ

좋아요 ~~ 코틀린 꼭 배워보고 싶어요  !

2021-05-22 05:04 UTC, saint6839 commented on profile/saint6839.md
> +에코노베이션에서 활동한지 그리 오래 되지 않았지만, 계속해서 좋은 기회들이 다가오고 좋은 정보들을 제공해주셔서 너무 감사하게 생각하고 있습니다. 앞으로도 행사에 최대한 참여하려고 노력하겠습니다. 마지막으로 방학때 코틀린 스터디가 꾸려지면 정말 좋을 것 같습니다 !
> 코틀린 스터디 좋네요ㅎㅎ 상엽님께서 앱개발자들으 모아서 한번 꾸려보시는건 어떤가요?ㅎㅎ

조금 걱정되긴 하지만 한번 생각해볼게요 ㅎㅎ 감사합니다 !

2021-05-22 05:06 UTC, saint6839 commented
> 에코노 21기 열정가이 상엽님 자기소개 잘봤어요 자기소개만으로도 열정이 느껴지네요~🔥
> 이번 학기 프로젝트도 화이팅입니다!!

멘토님들도 화이팅 입니다 !

2021-05-23 05:17 UTC, GiPyoo approved these changes

2021-05-23 05:17 UTC, GiPyoo commented on profile/saint6839.md
> +안녕하세요 산업공학과 3학년 재학중인 16학번 채상엽입니다.
산공 👍

2021-05-23 05:31 UTC, saint6839 commented on profile/saint6839.md
> +안녕하세요 산업공학과 3학년 재학중인 16학번 채상엽입니다.
> 산공 👍

안녕하세요 !! ㅎㅎ

2021-05-26 06:33 UTC, spiderq2697 approved these changes

2021-05-26 06:33 UTC, spiderq2697 commented on profile/sangyeop.md
> +이번 학기에는 첫 프로젝트로 Todo 어플리케이션을 구현합니다. 가장 단순하지만 기본이자 필수적인 기능들을 포함하고 있기 때문에, 첫 프로젝트 주제로 선정하였습니다. 대신에 저희는 완성도를 높히는 것에 초점을 맞출 계획입니다.
앱 개발이 이런거구나! 하고 한번 느끼는 그 과정도 정말 소중한 경험인 것 같아요ㅎㅎ

2021-05-31 13:58 UTC, gxxrxn approved these changes

2021-05-31 13:58 UTC, gxxrxn commented on profile/saint6839.md
> +안녕하세요 산업공학과 3학년 재학중인 16학번 채상엽입니다.
산공 분들이 정말 많은 것 같네요~!!ㅎㅎ👍

2021-05-31 13:58 UTC, gxxrxn commented on profile/saint6839.md
> +에코노베이션에서 활동한지 그리 오래 되지 않았지만, 계속해서 좋은 기회들이 다가오고 좋은 정보들을 제공해주셔서 너무 감사하게 생각하고 있습니다. 앞으로도 행사에 최대한 참여하려고 노력하겠습니다. 마지막으로 방학때 코틀린 스터디가 꾸려지면 정말 좋을 것 같습니다 !
코틀린 스터디!! 에코노베이션에 관심있는 분들 많을 것 같아요~!! 화이팅입니다!!

2021-07-01 09:50 UTC, merged

2021-07-01 09:50 UTC, mywnajsldkf commented
상엽님 merge조건 채우셔서 merge해드렸습니다! 축하드려요 :)

2021-07-03 15:07 UTC, saint6839 commented
> 상엽님 merge조건 채우셔서 merge해드렸습니다! 축하드려요 :)

감사합니다~!!