first_commit
JNU-econovation/2021-1-I-AM-GROUND pull request #7
Opened 2021-05-17 06:16 UTC by BlackBean99

first_commit

2021-05-17 07:12 UTC, mywnajsldkf requested changes
서현님의 자기소개 잘 봤습니다!
비대면인게 참 아쉽지만 이렇게라도 서현님을 알게되어 기뻐요!
pull request까지 이루신 점 축하드려요! 다만 라벨이 붙어있지않아 _Request changes_ 로 남겨두었습니다 이 부분 수정해 주시면 approve해드릴게요!!

2021-05-17 07:12 UTC, mywnajsldkf commented on profile/blackbean99.md
> +안녕하세요! 저는 에코노베이션 21기 이서현입니다^^ 저는 2학년이지만 18학번인데 군대를 다녀오니 벌써 3년이 지났습니다 ㅠㅠ.
우와!! 같은 18반갑습니당

2021-05-17 07:12 UTC, mywnajsldkf commented on profile/blackbean99.md
> + 저는 살아있는 또라이 Rh+AB형이라서 가만히 있는걸 정말 싫어합니다. 이름이 외자는 아니지만 외로움을 많이 타서, 아무것도 안하면 죄책감이 들어 운동을 하거나 공부를 하거나 적어도 산책이라도 가야하고 매일 있는 과제가 없으면 불안해질 정도 입니다.
서현님의 mbti가 궁금해지네요ㅋㅋ

2021-05-17 07:12 UTC, mywnajsldkf commented on profile/blackbean99.md
> +이번 학기에는 에코노 프로젝트로 인공지능에 도전합니다! "All-Rounder"라는 프로젝트명으로 자동투자인공지능 프로그램을 제작중입니다. 군대에서 책으로만 공부하다 실제로 도전해보니 설레기도 하고 불안하기도 합니다. 완성할 수 있을지 모르지만 저와 함께해주는 전남대학교 무적산공 다은님과 도움을 주시는 멘토 지우님, 영주님, 차영님이 있어서 든든합니다!
우와 카카오톡에 인공지능이 추천해주는 펀드...(?) 그거 있어서 하고 있는데 지금 마이너스입니다ㅠㅠ

2021-05-17 07:12 UTC, mywnajsldkf commented on profile/blackbean99.md
> +음악 듣는것도 정말 좋아하지만 저는 연주하는 것을 정말 좋아합니다. 하모니카든 기타든 피아노든 가리지 않아요. 특히 좋아하는 분야는 R&B입니다. 특히 Gallent-Weight in Gold, Samm Henshaw노래나 이바다 노래같은 보라색맛 노래를 좋아해요. 요즘은 다 내려놓고 기타만 치고 있는데 역시 어렵습니다ㅠㅠ 올해 목표는 Jazz R&B연주
오...!!! 에코노베이션에 뮤지션이 많이 계시네요

2021-05-17 07:12 UTC, mywnajsldkf commented on profile/blackbean99.md
> +누군가 저만의 특별한 장기가 있냐고 물어본다면 저는 저는 고민없이 커피타는 것이라고 이야기 하고 싶어요! 처음 만난 바리스타분과의 인연으로 커피를 배우기 시작했고, 어느새 제가 바리스타가 돼서 사람들에게 커피를 알리고 있어요. 커피를 전하는 이 행위는 저와 함께 하는 사람에게 새로운 대화 주제를 꺼낼 수 있게 만들어 주고 그사람의 무료한 하루를 값지게 만
우왓 카페사장...

2021-05-17 07:12 UTC, mywnajsldkf commented on profile/blackbean99.md
> +저는 본가에 가면 집에서 늘 신메뉴를 만들어 보고 있어요. 실패한 적도 많아서 엄마가 못믿는지경이지만.. 너무 재밌습니다. 수제짜장, 허브크러스트양갈비 타코 등 혀를 유린하는 요리들이 세상에 너무 많아요.
와우 야유회 가야겠군요🍱🍱

2021-05-17 07:12 UTC, mywnajsldkf commented on profile/blackbean99.md
> +응에 21기입니다. 에코노피플들 만나서 재밌는 이야기 많이 하고 친해지구 싶어요! 앞으로 잘부탁드려요!!
반갑습니다🙃🙃

2021-05-17 08:32 UTC, BlackBean99 commented on profile/blackbean99.md
> +안녕하세요! 저는 에코노베이션 21기 이서현입니다^^ 저는 2학년이지만 18학번인데 군대를 다녀오니 벌써 3년이 지났습니다 ㅠㅠ.
18학번이셨군요! 반가워요^^

2021-05-17 08:32 UTC, BlackBean99 commented on profile/blackbean99.md
> + 저는 살아있는 또라이 Rh+AB형이라서 가만히 있는걸 정말 싫어합니다. 이름이 외자는 아니지만 외로움을 많이 타서, 아무것도 안하면 죄책감이 들어 운동을 하거나 공부를 하거나 적어도 산책이라도 가야하고 매일 있는 과제가 없으면 불안해질 정도 입니다.
ENFJ 입니당

2021-05-17 08:33 UTC, BlackBean99 commented on profile/blackbean99.md
> +이번 학기에는 에코노 프로젝트로 인공지능에 도전합니다! "All-Rounder"라는 프로젝트명으로 자동투자인공지능 프로그램을 제작중입니다. 군대에서 책으로만 공부하다 실제로 도전해보니 설레기도 하고 불안하기도 합니다. 완성할 수 있을지 모르지만 저와 함께해주는 전남대학교 무적산공 다은님과 도움을 주시는 멘토 지우님, 영주님, 차영님이 있어서 든든합니다!
시중에 뿌려지는 투자인공지능은 믿을만하지...크흠

2021-05-17 08:33 UTC, BlackBean99 commented on profile/blackbean99.md
> +누군가 저만의 특별한 장기가 있냐고 물어본다면 저는 저는 고민없이 커피타는 것이라고 이야기 하고 싶어요! 처음 만난 바리스타분과의 인연으로 커피를 배우기 시작했고, 어느새 제가 바리스타가 돼서 사람들에게 커피를 알리고 있어요. 커피를 전하는 이 행위는 저와 함께 하는 사람에게 새로운 대화 주제를 꺼낼 수 있게 만들어 주고 그사람의 무료한 하루를 값지게 만
커피한잔할래용~~

2021-05-17 08:33 UTC, BlackBean99 commented on profile/blackbean99.md
> +음악 듣는것도 정말 좋아하지만 저는 연주하는 것을 정말 좋아합니다. 하모니카든 기타든 피아노든 가리지 않아요. 특히 좋아하는 분야는 R&B입니다. 특히 Gallent-Weight in Gold, Samm Henshaw노래나 이바다 노래같은 보라색맛 노래를 좋아해요. 요즘은 다 내려놓고 기타만 치고 있는데 역시 어렵습니다ㅠㅠ 올해 목표는 Jazz R&B연주
저말고 다른 뮤지션이 더 있나보군요!! 나중에 같이 합주하면 재밌겠어요 ㅎ

2021-05-17 08:34 UTC, BlackBean99 commented on profile/blackbean99.md
> +저는 본가에 가면 집에서 늘 신메뉴를 만들어 보고 있어요. 실패한 적도 많아서 엄마가 못믿는지경이지만.. 너무 재밌습니다. 수제짜장, 허브크러스트양갈비 타코 등 혀를 유린하는 요리들이 세상에 너무 많아요.
요리사로 써주십쇼!ㅋㅋ

2021-05-20 11:42 UTC, ummaeha commented on profile/blackbean99.md
> +음악 듣는것도 정말 좋아하지만 저는 연주하는 것을 정말 좋아합니다. 하모니카든 기타든 피아노든 가리지 않아요. 특히 좋아하는 분야는 R&B입니다. 특히 Gallent-Weight in Gold, Samm Henshaw노래나 이바다 노래같은 보라색맛 노래를 좋아해요. 요즘은 다 내려놓고 기타만 치고 있는데 역시 어렵습니다ㅠㅠ 올해 목표는 Jazz R&B연주
보라색맛 노래는 어떤 노래인가요?? 공감각적 심상인가! 👀 아직은 넘나 먼 음악의 세계!

2021-05-20 11:42 UTC, ummaeha commented on profile/blackbean99.md
> +누군가 저만의 특별한 장기가 있냐고 물어본다면 저는 저는 고민없이 커피타는 것이라고 이야기 하고 싶어요! 처음 만난 바리스타분과의 인연으로 커피를 배우기 시작했고, 어느새 제가 바리스타가 돼서 사람들에게 커피를 알리고 있어요. 커피를 전하는 이 행위는 저와 함께 하는 사람에게 새로운 대화 주제를 꺼낼 수 있게 만들어 주고 그사람의 무료한 하루를 값지게 만
행사부에서 에코노바리스타 데려갑니당~~~~😉

2021-05-20 11:45 UTC, ummaeha approved these changes
오늘부로 에코노 행사부와 함께 하게되신 서현님! 환영합니다~~~!!! approve!

![](https://media3.giphy.com/media/5GoVLqeAOo6PK/giphy.gif)

2021-05-21 16:04 UTC, vvvpiano approved these changes
재밌고 에너지 넘치는 자기소개 잘 읽었습니다!ㅎㅎ 반갑습니다 서현님!!

2021-05-21 16:04 UTC, vvvpiano commented on profile/blackbean99.md
> +안녕하세요! 저는 에코노베이션 21기 이서현입니다^^ 저는 2학년이지만 18학번인데 군대를 다녀오니 벌써 3년이 지났습니다 ㅠㅠ.
오 살아있는 신스틸러라고 본인을 요약하신 이유가 무엇인가요?ㅎㅎㅎ

2021-05-21 16:04 UTC, vvvpiano commented on profile/blackbean99.md
> + 이런 성격때문에 늘 배우는 걸 좋아하다 보니 발을 담군 분야가 너무 많아졌어요 ㅋㅋ 기회가 된다면 제가 경험하지 못한 분야도 도전해보고싶어요. 이번년도 버킷리스트는 별것 아니지만 클라이밍, 실내서핑, 온천가기 입니다. 여러분도 스포츠 좋아하시나요? 저에게 연락해주신다면 다양한 운동의 세계로 여러분을 초대하겠습니다!ㅎㅎ
관심사가 많고 취미가 많으면 나중에 지칠때 도피처가 많은것과 비슷하다고 들었어요ㅎㅎ 동력을 얻을곳이 많으시네요!

2021-05-21 16:04 UTC, vvvpiano commented on profile/blackbean99.md
> +음악 듣는것도 정말 좋아하지만 저는 연주하는 것을 정말 좋아합니다. 하모니카든 기타든 피아노든 가리지 않아요. 특히 좋아하는 분야는 R&B입니다. 특히 Gallent-Weight in Gold, Samm Henshaw노래나 이바다 노래같은 보라색맛 노래를 좋아해요. 요즘은 다 내려놓고 기타만 치고 있는데 역시 어렵습니다ㅠㅠ 올해 목표는 Jazz R&B연주
재즈 알앤비 정말 어려운 장르같은데 대단하시네요! 이정도면 에코노 동방에 피아노랑 기타도 들여놔야 할 판이네요ㅋㅋㅋㅋ한번씩 연주하는 회원님들 많으실듯ㅎㅎ

2021-05-21 16:04 UTC, vvvpiano commented on profile/blackbean99.md
> +누군가 저만의 특별한 장기가 있냐고 물어본다면 저는 저는 고민없이 커피타는 것이라고 이야기 하고 싶어요! 처음 만난 바리스타분과의 인연으로 커피를 배우기 시작했고, 어느새 제가 바리스타가 돼서 사람들에게 커피를 알리고 있어요. 커피를 전하는 이 행위는 저와 함께 하는 사람에게 새로운 대화 주제를 꺼낼 수 있게 만들어 주고 그사람의 무료한 하루를 값지게 만
저는 카페인을 잘 못마셔서 특별히 바쁜 기간이 아니면 커피는 디카페인을 마시고 있는데 고구마껍질 탄맛밖에 안나요ㅠㅠ 추천해주시는 디카페인 커피 있으신가요??

2021-05-21 16:04 UTC, vvvpiano commented on profile/blackbean99.md
> +저는 본가에 가면 집에서 늘 신메뉴를 만들어 보고 있어요. 실패한 적도 많아서 엄마가 못믿는지경이지만.. 너무 재밌습니다. 수제짜장, 허브크러스트양갈비 타코 등 혀를 유린하는 요리들이 세상에 너무 많아요.
야유회 가서 서현님 요리를 꼭 맛보고 싶네요!!

2021-05-21 16:04 UTC, vvvpiano commented on profile/blackbean99.md
> +응에 21기입니다. 에코노피플들 만나서 재밌는 이야기 많이 하고 친해지구 싶어요! 앞으로 잘부탁드려요!!
세상에 재밌는게 너무 많다고 느낄때만큼 삶의 의욕이 솟아날때는 없는것 같아요! 저는 일단 제 한정된 에너지를 학교공부와 개발공부에 쏟고 있지만..! 하고싶은 일들 리스트를 세워서 하나씩 해보면서 살고 싶네요ㅎㅎ

2021-05-22 06:38 UTC, BlackBean99 commented on profile/blackbean99.md
> +안녕하세요! 저는 에코노베이션 21기 이서현입니다^^ 저는 2학년이지만 18학번인데 군대를 다녀오니 벌써 3년이 지났습니다 ㅠㅠ.
늘 가장 먼저 나서지는 않지만 한박자 뒤에 나타나 캐릭터를 보여주는 성격이랄까요??

2021-05-22 06:44 UTC, BlackBean99 commented on profile/blackbean99.md
> +누군가 저만의 특별한 장기가 있냐고 물어본다면 저는 저는 고민없이 커피타는 것이라고 이야기 하고 싶어요! 처음 만난 바리스타분과의 인연으로 커피를 배우기 시작했고, 어느새 제가 바리스타가 돼서 사람들에게 커피를 알리고 있어요. 커피를 전하는 이 행위는 저와 함께 하는 사람에게 새로운 대화 주제를 꺼낼 수 있게 만들어 주고 그사람의 무료한 하루를 값지게 만
콜롬비아 EA 프로세싱 디카페인 종류를 찾아보세요! 그치만.. 카페인이 없으면 커피느낌이 나지 않는걸..

2021-05-22 09:52 UTC, asong57 approved these changes
서현님 환영합니다~~!!
행사부에서도 잘 해보아요!!

2021-05-22 09:52 UTC, asong57 commented on profile/blackbean99.md
> +음악 듣는것도 정말 좋아하지만 저는 연주하는 것을 정말 좋아합니다. 하모니카든 기타든 피아노든 가리지 않아요. 특히 좋아하는 분야는 R&B입니다. 특히 Gallent-Weight in Gold, Samm Henshaw노래나 이바다 노래같은 보라색맛 노래를 좋아해요. 요즘은 다 내려놓고 기타만 치고 있는데 역시 어렵습니다ㅠㅠ 올해 목표는 Jazz R&B연주
저는 옆에서 박수 열심히 치겠습니다! ㅋㅋ

2021-05-22 09:52 UTC, asong57 commented on profile/blackbean99.md
> +저는 본가에 가면 집에서 늘 신메뉴를 만들어 보고 있어요. 실패한 적도 많아서 엄마가 못믿는지경이지만.. 너무 재밌습니다. 수제짜장, 허브크러스트양갈비 타코 등 혀를 유린하는 요리들이 세상에 너무 많아요.
에코노 야유회ㅠㅠ꼭 가고싶네용!

2021-05-22 16:30 UTC, hotheadfactory commented on profile/blackbean99.md
> + 저는 살아있는 또라이 Rh+AB형이라서 가만히 있는걸 정말 싫어합니다. 이름이 외자는 아니지만 외로움을 많이 타서, 아무것도 안하면 죄책감이 들어 운동을 하거나 공부를 하거나 적어도 산책이라도 가야하고 매일 있는 과제가 없으면 불안해질 정도 입니다.
저도 AB형입니다. 반갑네요~

2021-05-23 05:21 UTC, GiPyoo commented on profile/blackbean99.md
> +누군가 저만의 특별한 장기가 있냐고 물어본다면 저는 저는 고민없이 커피타는 것이라고 이야기 하고 싶어요! 처음 만난 바리스타분과의 인연으로 커피를 배우기 시작했고, 어느새 제가 바리스타가 돼서 사람들에게 커피를 알리고 있어요. 커피를 전하는 이 행위는 저와 함께 하는 사람에게 새로운 대화 주제를 꺼낼 수 있게 만들어 주고 그사람의 무료한 하루를 값지게 만
오 커피마스터

2021-05-23 05:22 UTC, GiPyoo commented on profile/blackbean99.md
> +저는 본가에 가면 집에서 늘 신메뉴를 만들어 보고 있어요. 실패한 적도 많아서 엄마가 못믿는지경이지만.. 너무 재밌습니다. 수제짜장, 허브크러스트양갈비 타코 등 혀를 유린하는 요리들이 세상에 너무 많아요.
요리마스터

2021-05-23 05:22 UTC, GiPyoo commented on profile/blackbean99.md
> +이번 학기에는 에코노 프로젝트로 인공지능에 도전합니다! "All-Rounder"라는 프로젝트명으로 자동투자인공지능 프로그램을 제작중입니다. 군대에서 책으로만 공부하다 실제로 도전해보니 설레기도 하고 불안하기도 합니다. 완성할 수 있을지 모르지만 저와 함께해주는 전남대학교 무적산공 다은님과 도움을 주시는 멘토 지우님, 영주님, 차영님이 있어서 든든합니다!
ai 인재

2021-05-23 05:23 UTC, GiPyoo approved these changes
welcome 서현

2021-05-23 05:23 UTC, GiPyoo commented on profile/blackbean99.md
> +더 많이 도전해보고 더 다양한 국가의 맛을 만들어 보고 싶어요. 제 요리 도전은 멈추지 않습니다.  - 오늘 준비한 고기부터보시죠
이런 인재가 에코노베이션에!!

2021-05-26 06:42 UTC, spiderq2697 approved these changes

2021-05-26 06:42 UTC, spiderq2697 commented on profile/blackbean99.md
> + 저는 살아있는 또라이 Rh+AB형이라서 가만히 있는걸 정말 싫어합니다. 이름이 외자는 아니지만 외로움을 많이 타서, 아무것도 안하면 죄책감이 들어 운동을 하거나 공부를 하거나 적어도 산책이라도 가야하고 매일 있는 과제가 없으면 불안해질 정도 입니다.
저도 AB형인데ㅎㅎ

2021-05-26 06:42 UTC, spiderq2697 commented on profile/blackbean99.md
> + 저는 살아있는 또라이 Rh+AB형이라서 가만히 있는걸 정말 싫어합니다. 이름이 외자는 아니지만 외로움을 많이 타서, 아무것도 안하면 죄책감이 들어 운동을 하거나 공부를 하거나 적어도 산책이라도 가야하고 매일 있는 과제가 없으면 불안해질 정도 입니다.
저도 ENFJ인데??ㅋㅋㅋㅋㅋ

2021-05-26 06:42 UTC, spiderq2697 commented on profile/blackbean99.md
> + 이런 성격때문에 늘 배우는 걸 좋아하다 보니 발을 담군 분야가 너무 많아졌어요 ㅋㅋ 기회가 된다면 제가 경험하지 못한 분야도 도전해보고싶어요. 이번년도 버킷리스트는 별것 아니지만 클라이밍, 실내서핑, 온천가기 입니다. 여러분도 스포츠 좋아하시나요? 저에게 연락해주신다면 다양한 운동의 세계로 여러분을 초대하겠습니다!ㅎㅎ
시흥에 동아시아 최대 규모의 실내 서핑장이 생겼는데 코로나 상황보고 이번 여름은 거기로 계획중에 있습니다ㅎㅎ 서현님도 한번 생각해보세요ㅎㅎ

2021-05-26 06:42 UTC, spiderq2697 commented on profile/blackbean99.md
> + 이런 성격때문에 늘 배우는 걸 좋아하다 보니 발을 담군 분야가 너무 많아졌어요 ㅋㅋ 기회가 된다면 제가 경험하지 못한 분야도 도전해보고싶어요. 이번년도 버킷리스트는 별것 아니지만 클라이밍, 실내서핑, 온천가기 입니다. 여러분도 스포츠 좋아하시나요? 저에게 연락해주신다면 다양한 운동의 세계로 여러분을 초대하겠습니다!ㅎㅎ
전대 후문에 핸드워크 클라이밍장있는데 초심자로서 하기에는 좋은 거 같아요. 좁아보일 수 있는데 사장님이 문제도 한달마다 바꿔주시고 해서 문제 풀다보면 시간 후딱 가있더라구요ㅎㅎ

2021-05-26 06:42 UTC, spiderq2697 commented on profile/blackbean99.md
> +이번 학기에는 에코노 프로젝트로 인공지능에 도전합니다! "All-Rounder"라는 프로젝트명으로 자동투자인공지능 프로그램을 제작중입니다. 군대에서 책으로만 공부하다 실제로 도전해보니 설레기도 하고 불안하기도 합니다. 완성할 수 있을지 모르지만 저와 함께해주는 전남대학교 무적산공 다은님과 도움을 주시는 멘토 지우님, 영주님, 차영님이 있어서 든든합니다!
무적산공 다은님과 함께 무적 인공지능 결과물을 만들어주세요ㅎㅎ

2021-05-26 06:42 UTC, spiderq2697 commented on profile/blackbean99.md
> +음악 듣는것도 정말 좋아하지만 저는 연주하는 것을 정말 좋아합니다. 하모니카든 기타든 피아노든 가리지 않아요. 특히 좋아하는 분야는 R&B입니다. 특히 Gallent-Weight in Gold, Samm Henshaw노래나 이바다 노래같은 보라색맛 노래를 좋아해요. 요즘은 다 내려놓고 기타만 치고 있는데 역시 어렵습니다ㅠㅠ 올해 목표는 Jazz R&B연주
보라색 맛이면 아이유?.... 죄송합니다 ㅋㅋㅋ

2021-05-26 06:42 UTC, spiderq2697 commented on profile/blackbean99.md
> +누군가 저만의 특별한 장기가 있냐고 물어본다면 저는 저는 고민없이 커피타는 것이라고 이야기 하고 싶어요! 처음 만난 바리스타분과의 인연으로 커피를 배우기 시작했고, 어느새 제가 바리스타가 돼서 사람들에게 커피를 알리고 있어요. 커피를 전하는 이 행위는 저와 함께 하는 사람에게 새로운 대화 주제를 꺼낼 수 있게 만들어 주고 그사람의 무료한 하루를 값지게 만
커피, 재즈, 색소폰이면 나중에 라이브카페 하시면 너무 좋을 것 같네요. 생각하고 있으니깐 재즈를 배우고 싶은 생각이 갑자기 확 드네요ㅋㅋ

2021-05-26 10:59 UTC, BlackBean99 commented on profile/blackbean99.md
> + 저는 살아있는 또라이 Rh+AB형이라서 가만히 있는걸 정말 싫어합니다. 이름이 외자는 아니지만 외로움을 많이 타서, 아무것도 안하면 죄책감이 들어 운동을 하거나 공부를 하거나 적어도 산책이라도 가야하고 매일 있는 과제가 없으면 불안해질 정도 입니다.
AB형들 모여라! ㅋㅋㅋ

2021-05-26 11:00 UTC, BlackBean99 commented on profile/blackbean99.md
> +이번 학기에는 에코노 프로젝트로 인공지능에 도전합니다! "All-Rounder"라는 프로젝트명으로 자동투자인공지능 프로그램을 제작중입니다. 군대에서 책으로만 공부하다 실제로 도전해보니 설레기도 하고 불안하기도 합니다. 완성할 수 있을지 모르지만 저와 함께해주는 전남대학교 무적산공 다은님과 도움을 주시는 멘토 지우님, 영주님, 차영님이 있어서 든든합니다!
크흑.. 최선을 다해볼게요!

2021-05-26 11:00 UTC, BlackBean99 commented on profile/blackbean99.md
> +저는 본가에 가면 집에서 늘 신메뉴를 만들어 보고 있어요. 실패한 적도 많아서 엄마가 못믿는지경이지만.. 너무 재밌습니다. 수제짜장, 허브크러스트양갈비 타코 등 혀를 유린하는 요리들이 세상에 너무 많아요.
마스터라고 그만해요 ㅋㅋ 그정돈 아님다!ㅋㅋ

2021-05-26 11:01 UTC, BlackBean99 commented on profile/blackbean99.md
> + 이런 성격때문에 늘 배우는 걸 좋아하다 보니 발을 담군 분야가 너무 많아졌어요 ㅋㅋ 기회가 된다면 제가 경험하지 못한 분야도 도전해보고싶어요. 이번년도 버킷리스트는 별것 아니지만 클라이밍, 실내서핑, 온천가기 입니다. 여러분도 스포츠 좋아하시나요? 저에게 연락해주신다면 다양한 운동의 세계로 여러분을 초대하겠습니다!ㅎㅎ
오오 좋은정보 고마워요!! 꼭 가봐야겠네용

2021-05-26 11:54 UTC, mywnajsldkf commented
@BlackBean99 오~~ 서현님! 멋지게 label 달아주셨군요 굿입니다 굿이에요!! Approve 해드릴게요!ㅎㅎ

2021-05-26 11:55 UTC, mywnajsldkf approved these changes

2021-05-27 12:45 UTC, JUDONGHYEOK approved these changes

2021-05-27 12:45 UTC, JUDONGHYEOK commented on profile/blackbean99.md
> +이번 학기에는 에코노 프로젝트로 인공지능에 도전합니다! "All-Rounder"라는 프로젝트명으로 자동투자인공지능 프로그램을 제작중입니다. 군대에서 책으로만 공부하다 실제로 도전해보니 설레기도 하고 불안하기도 합니다. 완성할 수 있을지 모르지만 저와 함께해주는 전남대학교 무적산공 다은님과 도움을 주시는 멘토 지우님, 영주님, 차영님이 있어서 든든합니다!
결과물이 나온다면 꼭 써보고싶네요!! 제 자산을 불기둥으로 만들어주세요~~

2021-05-27 12:45 UTC, JUDONGHYEOK commented on profile/blackbean99.md
> +음악 듣는것도 정말 좋아하지만 저는 연주하는 것을 정말 좋아합니다. 하모니카든 기타든 피아노든 가리지 않아요. 특히 좋아하는 분야는 R&B입니다. 특히 Gallent-Weight in Gold, Samm Henshaw노래나 이바다 노래같은 보라색맛 노래를 좋아해요. 요즘은 다 내려놓고 기타만 치고 있는데 역시 어렵습니다ㅠㅠ 올해 목표는 Jazz R&B연주
오 하모니카는 되게 신선하네요 언제 한 번 연주하시는거 들려주세요~~

2021-05-27 12:45 UTC, JUDONGHYEOK commented on profile/blackbean99.md
> +저는 본가에 가면 집에서 늘 신메뉴를 만들어 보고 있어요. 실패한 적도 많아서 엄마가 못믿는지경이지만.. 너무 재밌습니다. 수제짜장, 허브크러스트양갈비 타코 등 혀를 유린하는 요리들이 세상에 너무 많아요.
저는 옆에서 열심히 먹겠습니다!!

2021-05-27 12:45 UTC, JUDONGHYEOK commented on profile/blackbean99.md
> +응에 21기입니다. 에코노피플들 만나서 재밌는 이야기 많이 하고 친해지구 싶어요! 앞으로 잘부탁드려요!!
21기분들을 아직 화면으로밖에 못봐서 아쉬워요ㅜㅜ 언제 기회되면 얼굴 보면서 얘기해요~~

2021-05-31 14:29 UTC, gxxrxn approved these changes

2021-05-31 14:29 UTC, gxxrxn commented on profile/blackbean99.md
> +안녕하세요! 저는 전남대학교의 살아있는 신스틸러 이서현입니다!!
ㅋㅋㅋ살아있는 신스틸러!!! 👍

2021-05-31 14:29 UTC, gxxrxn commented on profile/blackbean99.md
> + 저는 살아있는 또라이 Rh+AB형이라서 가만히 있는걸 정말 싫어합니다. 이름이 외자는 아니지만 외로움을 많이 타서, 아무것도 안하면 죄책감이 들어 운동을 하거나 공부를 하거나 적어도 산책이라도 가야하고 매일 있는 과제가 없으면 불안해질 정도 입니다.
오.. 저도 AB... 전 또라이 아닌데요.....ㅠ 또라이 안할래요....ㅠㅠ

2021-05-31 14:29 UTC, gxxrxn commented on profile/blackbean99.md
> + 이런 성격때문에 늘 배우는 걸 좋아하다 보니 발을 담군 분야가 너무 많아졌어요 ㅋㅋ 기회가 된다면 제가 경험하지 못한 분야도 도전해보고싶어요. 이번년도 버킷리스트는 별것 아니지만 클라이밍, 실내서핑, 온천가기 입니다. 여러분도 스포츠 좋아하시나요? 저에게 연락해주신다면 다양한 운동의 세계로 여러분을 초대하겠습니다!ㅎㅎ
역시 행사부 인재!!!👍

2021-05-31 14:29 UTC, gxxrxn commented on profile/blackbean99.md
> +이번 학기에는 에코노 프로젝트로 인공지능에 도전합니다! "All-Rounder"라는 프로젝트명으로 자동투자인공지능 프로그램을 제작중입니다. 군대에서 책으로만 공부하다 실제로 도전해보니 설레기도 하고 불안하기도 합니다. 완성할 수 있을지 모르지만 저와 함께해주는 전남대학교 무적산공 다은님과 도움을 주시는 멘토 지우님, 영주님, 차영님이 있어서 든든합니다!
차영님 누구야~~~~ㅋㅋㅋㅋ 다은님과 함께 열심히 하는 모습 진짜 너무 보기 좋아요!!😆👍

2021-05-31 14:29 UTC, gxxrxn commented on profile/blackbean99.md
> +음악 듣는것도 정말 좋아하지만 저는 연주하는 것을 정말 좋아합니다. 하모니카든 기타든 피아노든 가리지 않아요. 특히 좋아하는 분야는 R&B입니다. 특히 Gallent-Weight in Gold, Samm Henshaw노래나 이바다 노래같은 보라색맛 노래를 좋아해요. 요즘은 다 내려놓고 기타만 치고 있는데 역시 어렵습니다ㅠㅠ 올해 목표는 Jazz R&B연주
앗! 그렇다면..!! 아까 윤성님 PR에서도 언급했지만..!!
제가 치려다가 포기한 샘김 - 그여름밤 신청합니다!!🥺

2021-05-31 14:29 UTC, gxxrxn commented on profile/blackbean99.md
> +잡생각이 없어지는게 너무 좋아요. 2월까지는 헬스장을 다니다가 복학하고 요즘은 유산소만 하고 있어요 싸이클을 타거나 러닝하는 것도 너무 재밌어요! 여름맞이 헬스장을 다시 갈지 고민중인데 코로나라 걱정만 가득합니다.ㅠㅠ
저도... 코로나를 핑계대며 미루고 미루는중.......하핫!

2021-05-31 14:29 UTC, gxxrxn commented on profile/blackbean99.md
> +요즘 시대에 플랫폼도 너무 잘돼있고 개발하기 딱 좋은 환경인 것 같아요. 쓸 곳도 정말 무궁무진합니다. 공부를 하고 있지만, 이론이 정말 어려워서 힘든점이 있긴 합니다ㅠ 이게 프로그래밍인지 통계학전공인지 구분이 안가는.. 더 열심히 해서 많이 써보고 싶어요.
,,,,ㅠㅠ 인공지능.... 수학이 너무 싫어요 전...... 서현님 리스펙👍

2021-05-31 14:29 UTC, gxxrxn commented on profile/blackbean99.md
> +저는 본가에 가면 집에서 늘 신메뉴를 만들어 보고 있어요. 실패한 적도 많아서 엄마가 못믿는지경이지만.. 너무 재밌습니다. 수제짜장, 허브크러스트양갈비 타코 등 혀를 유린하는 요리들이 세상에 너무 많아요.
ㅋㅋㅋㅋㅋ 커피마스터 요리마스터 운동마스터 못하는게 뭐야~~~

2021-05-31 14:29 UTC, gxxrxn commented on profile/blackbean99.md
> +더 많이 도전해보고 더 다양한 국가의 맛을 만들어 보고 싶어요. 제 요리 도전은 멈추지 않습니다.  - 오늘 준비한 고기부터보시죠
이런 인재가 에코노베이션 행사부에!!

2021-05-31 14:29 UTC, gxxrxn commented on profile/blackbean99.md
> +최근에 족저근막염이랑 회전근개충돌 부상을 당했지만 거의다 회복했습니다. 에코노여러분은 부상조심하세요.. 진짜 아파서 운동못하는 것만큼 슬픈게 없더라구요ㅠㅠ
건강이 최고!!

2021-05-31 14:29 UTC, gxxrxn commented on profile/blackbean99.md
> +응에 21기입니다. 에코노피플들 만나서 재밌는 이야기 많이 하고 친해지구 싶어요! 앞으로 잘부탁드려요!!
자주 만나요~~!! 행사부에 들어오신걸 환영합니다~!!😆

2021-07-01 09:53 UTC, merged

2021-07-01 09:53 UTC, mywnajsldkf commented
서현님 merge조건 채우셔서 merge해드렸습니다! 축하드려요!